services:
  db:
    image: 'postgres:16'
    environment:
      - POSTGRES_USER=t
      - POSTGRES_PASSWORD=g
      - POSTGRES_DB=taskly
    container_name: databaseTaskly
    networks:
      - tasklynetwork
    ports:
      - "5432:5432"
    volumes:
      - ./database/volumes/data:/var/lib/postgresql/data
      - ./database/sql/:/docker-entrypoint-initdb.d/

  app:
    build:  ./backend/taskly
    container_name: backendTaskly
    depends_on:
      - db
    networks:
      - tasklynetwork
    ports:
      - "8080:8080"

networks:
  tasklynetwork:
    driver: bridge
